### ISSUE TITLE
Role docker.geerlingguy not found with bootstrap command

### ISSUE THREAD

**Issue by tislam93** [ChameleonCloud/python-chi-edge#7]
python -m chi_edge bootstrap might show this error. Seems like this is a bug in ansible-galaxy and I found it's fix by `export ANSIBLE_ROLES_PATH=/.venv/share/ansible/roles/geerlingguy.docker`. By default it would point to a different path so the environment variable needs to be set. As a reference this [link](https://github.com/ansible-community/molecule/issues/1093) has more information on a similar issue.

**Comment by msherman64** [comment]
this was incidentally resolved in https://github.com/ChameleonCloud/python-chi-edge/commit/0cfb7197699393318daafe59dda985782e95df88 by the removal of all ansible code.
